.TH BWMAN 1 "11 April 2012"
.SH NAME
bwman \- Password manager using bash and gnupg
.SH SYNOPSIS
.B bwman
.RB [ \-ehl ]
.RB [ \-a | \-d | \-m | \-p | \-y
.IR NAME ]
.SH DESCRIPTION
bwman (bashword manager) is a password manager for bash. It keeps passwords in a
gpg-encrypted text file. Single action is allowed per invocation.
.P
Before using bwman, you must create yourself a gpg key, which will be used when
encrypting the password-file.
.P
.RS
.B gpg2 \-\-gen\-key
.RE
.P
Then create a file named bwman.asc, put it in
.I ~/.local/share/bwman/
and encrypt it with gpg. This will be your password-file.
.P
.RS
.B mkdir \fI~/.local/share/bwman\fP

.B touch \fI~/.local/share/bwman/bwman.asc\fP

.B gpg2 --encrypt --armor --recipient
.I GPG-USERNAME ~/.local/share/bwman/bwman.asc
.RE
.P
Now you can start adding your passwords to the password-file with the
.B -a
switch. You can also edit the password-file directly with the
.B -e
switch.
.SH OPTIONS
.TP
.BI "\-a " NAME
Add service \fINAME\fP to the password-file.
.TP
.BI "\-d " NAME
Delete service \fINAME\fP from the password-file.
.TP
.B \-e
Edit the password-file with an editor specified by $EDITOR. In case $EDITOR is
not set, user is prompted to specify the editor to use.
.TP
.B \-h
Print usage instructions.
.TP
.B \-l
Print a list of all services.
.TP
.BI "\-m " NAME
Modify the name, username or password of \fINAME\fP.
.TP
.BI "\-p " NAME
Print the username and password of \fINAME\fP.
.TP
.BI "\-y " NAME
Yank the password of \fINAME\fP to the primary selection and the username of
\fINAME\fP to the clipboard selection. Paste the username with \fBC-V\fP
and the password with either middle-clicking the mouse or pressing \fBS-Insert\fP.
.SH FILES
.TP
.B /etc/bwman.conf
Global configuration file
.TP
.B ~/.config/bwman/bwman.conf
User configuration file
.TP
.B ~/.local/share/bwman/bwman.asc
Password-file
.SH NOTES
.TP
.B Password-file format
.RS
[SERVICE][SPACE(S)][USERNAME][SPACE(S)][PASSWORD]
.RE
.SH BUGS
.EX
No spaces are allowed in usernames, passwords or service names because of the
way the passwords are currently stored. See \fBNOTES\fP.
.EE
.SH AUTHOR
.EX
schalox <schalox at gmail dot com>
.EE
.SH SEE ALSO
.BR pwsafe (1)
